version: "3.8"

services:
  flask_app:
    build: "."
    command: gunicorn --bind 0.0.0.0:4200 app_data:app
    restart: always
    ports:
      - "4200:4200"
    environment:
      - DB_TYPE=postgresql
      - DB_USER=robot
      - DB_PASSWORD=robot
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=robot
    depends_on:
      - database

  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=robot
      - POSTGRES_PASSWORD=robot
      - POSTGRES_DB=robot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app

  volumes:
    postgres_data: